In [3]:
import tensorflow as tf
tf.__version__

'2.8.0'

# 0-Rank Tensor

In [4]:
scaler = tf.Variable(8, dtype=tf.float64, name='scaler')
scaler

<tf.Variable 'scaler:0' shape=() dtype=float64, numpy=8.0>

In [5]:
# Extracting as Numpy
scaler.numpy()

8.0

In [6]:
# get the rank
tf.rank(scaler)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

# 1- Rank Tensor

In [7]:
vector = tf.Variable([2,3,4,5], dtype=tf.float64, name='vector')
vector

<tf.Variable 'vector:0' shape=(4,) dtype=float64, numpy=array([2., 3., 4., 5.])>

In [8]:
vector.numpy()

array([2., 3., 4., 5.])

In [9]:
tf.rank(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

# 2 - Rank Tensor

In [11]:
matrix = tf.Variable([[2,3,4], [7,3,4],[ 2, 5.5, 6.6]], dtype=tf.float64, name='matrix')
matrix

<tf.Variable 'matrix:0' shape=(3, 3) dtype=float64, numpy=
array([[2. , 3. , 4. ],
       [7. , 3. , 4. ],
       [2. , 5.5, 6.6]])>

In [12]:
tf.rank(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# 3 Rank Tensor

In [14]:
image = tf.constant([2,3,4,5,6,7,8,9], shape=(2,2,2), dtype=tf.float64, name='image')
image

<tf.Tensor: shape=(2, 2, 2), dtype=float64, numpy=
array([[[2., 3.],
        [4., 5.]],

       [[6., 7.],
        [8., 9.]]])>

In [15]:
tf.rank(image)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

# Instant Tensor Creation

In [16]:
tf.eye(3,3, dtype=tf.float64)

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])>

In [17]:
tf.fill([3,3], 9)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])>

In [19]:
tf.linspace(1,10, 20)

<tf.Tensor: shape=(20,), dtype=float64, numpy=
array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])>

In [20]:
tf.ones([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [23]:
tf.zeros([4,8])

<tf.Tensor: shape=(4, 8), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [25]:
tf.random.normal([3,3], mean=1, stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.70598406,  1.1053305 , -0.15803266],
       [ 1.620048  , -1.1960993 ,  1.126086  ],
       [ 0.36006296,  2.5262127 , -0.16080177]], dtype=float32)>